server:
  port: 8081

spring:
  profiles:
    # 外置jdbc、redis和mail配置文件
    active: jdbc,redis,mail,test
  # 关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
  # 配置国际化资源文件
  messages:
    basename: i18n.logo



    # MyBatis配置
mybatis:
  configuration:
    #开启驼峰命名匹配映射
    map-underscore-to-camel-case: true

    #控制台打印日志，能打印出被扫描的包和被解析的映射文件
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  #配置MyBatis的xml映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #######配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.itheima.mybolg.model.domain


######mybatis日志显示SQL
logging:
  level:
    com.itheima.myblog.mapper: debug

#pagehelper分页设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#浏览器cookie相关设置
COOKIE:
  # 设置cookie默认时长为30分钟
  VALIDITY: 1800

